---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# predictlm

<!-- badges: start -->
<!-- badges: end -->

The goal of predictlm is to provide an R interface to PredictLM model checkpoints from Zero One Research. For more information please see the official website: https://zerooneresearch.ai/models/

## Installation

You can install the development version of predictlm like so:

``` r
pak::pak('frankiethull/predictlm')
```

## Example

```{r example}
library(predictlm)
library(rsample)

corn_data <- maize::corn_data

corn_splits <- initial_validation_split(corn_data)
train <- training(corn_splits)
validate <- validation(corn_splits)
test <- testing(corn_splits)
```

### Classification

```{r}
fit_cls <- predictlm_fit(
  train |> dplyr::select(-type),
  train$type,
  device = "cpu"
)

class_preds <- predictlm_predict(fit_cls, test |> dplyr::select(-type))

class_preds |> head()
```

### Regression

```{r}
fit_reg <- predictlm_fit(
  train |> dplyr::select(-height, -type),
  train$height,
  problem_type = "regression",
  device = "cpu"
)

preds <- predictlm_predict(fit_reg, test |> dplyr::select(-height, -type))

preds |> head()
```